### ISSUE TITLE
Issues with log levels

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-jetty#112]
I have `bootique-logback` and `bootique-jetty` modules in a simple app. The following two configurations (root logger "off", Jetty logger "off") should both result in suppressing Jetty logs completely. Yet they don't...

```yaml
log:
  level: "off"
```

```yaml
log:
  loggers:
    org.eclipse.jetty :
      level: "off"
```

```
INFO  [2022-01-31 13:31:05,014] main o.e.jetty.util.log: Logging initialized @678ms to org.eclipse.jetty.util.log.Slf4jLog
```
Only when I combine the two, I can silence the log:
```yaml
log:
  level: "off"
  loggers:
    org.eclipse.jetty :
      level: "off"
```
