### ISSUE TITLE
Unable to set connector host to `*`

### ISSUE THREAD

**Issue by stariy95** [bootique/bootique-jetty#119]
[Documentation](https://bootique.io/docs/2.x/bootique-jetty-docs/#_jetty_connectors) states that `*` value is default and means listen to all hosts. This works perfectly fine if host parameter is missing in the config but when this value is used explicitly it leads to an error like this:
`Failed to bind to */<unresolved>:8080`

Configuration to test this:
```yaml
jetty:
  connectors:
    - host: '*'
      port: 8080
      type: http
```
