### ISSUE TITLE
SSL connector

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-jetty#42]
We need to support SSL connectors in Jetty.

**Comment by andrus** [comment]
Done. Now something a configuration like this should stand up an SSL connector:

```yaml
jetty:
  connectors:
    - type: https
      port: 14001
      keyStore: 'classpath:mykeystore'
      keyStorePassword: 'supersecret'
      certificateAlias: mycert
```
