### ISSUE TITLE
Use percentage metric for thread pool utilization check

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-jetty#77]
`PercentValueRangeFactory` is now available per https://github.com/bootique/bootique-metrics/issues/27 . Let's switch Jetty metrics to percentages instead of doubles. 

## UPGRADE NOTES

In the following config:
```yaml
jetty:
  health:
    poolUtilizationThreshold: "0.6 0.9"
```
fractions should be replaced with percentages:
```yaml
jetty:
  health:
    poolUtilizationThresholds:
      warning: 60%
      critical: 90%
```
