### ISSUE TITLE
Support connector "idleTimeout" property in config

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-jetty#86]
Currently idle timeout in the connector is hardcoded to be `30 * 1000`. Let's make it a config property:

```yaml
jetty:
    connectors:
         - port: 8080
           idleTimeout: '20s'
```
