### ISSUE TITLE
Turning off "Server" header

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-jetty#88]
Currently Bootique Jetty apps are hardcoded to include `Server: Jetty(9.4.z-SNAPSHOT)` header in responses. Occasionally people would like to turn it off, e.g. for security reasons. 

In Jetty 9, this a [config property of the connector](https://stackoverflow.com/questions/15652902/remove-the-http-server-header-in-jetty-9). Specifically in Bootique this property is set in `ConnectorFactory.buildHttpConfiguration`.

Per this task we will make the `Server` header `false` by default and will support the way to explicitly change it to true per connector. E.g.:

```yaml
jetty:
   connectors:
       - port: 10000
         sendServerVersion: true
```
