### ISSUE TITLE
"any" port - selecting port dynamically

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-jetty#98]
Sometimes it is beneficial to start Jetty on an arbitrary free port. E.g. [during the unit tests](https://github.com/bootique/bootique-jetty/issues/97) it helps to avoid port conflicts. Let's add support for specifying a dynamic port in configuration:

```yaml
# EXISTING: explicit numeric port
jetty:
  connectors:
    - type: http
      port: 8081 
```

```yaml
# EXISTING: implicit port 8080
jetty:
  connectors:
    - type: http
```

```yaml
# NEW: dynamic port determined in runtime
jetty:
  connectors:
    - type: http
      port: any
```
